# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-25 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt', '0002_remove_wish_liked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked_wishes', to='belt.User'),
        ),
    ]
