# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-25 18:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('belt', '0003_wish_liked_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wish',
            name='liked_by',
        ),
    ]
