# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-22 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote_dash', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked_quotes', to='quote_dash.User'),
        ),
    ]
