# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-22 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt', '0002_auto_20181022_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
